// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://axofngdsxsdpdbwxipkk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF4b2ZuZ2RzeHNkcGRid3hpcGtrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxOTkyOTIsImV4cCI6MjA2Mzc3NTI5Mn0.hbUHK5RAAIiFf3jC-LE7EMRtZWl8HqUfDbfM6lmiBWg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);